# Generated by Django 3.2.8 on 2021-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
