# Generated by Django 3.2.8 on 2021-11-01 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
