# Generated by Django 3.2.8 on 2021-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_otp_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='time_created',
            field=models.IntegerField(),
        ),
    ]
