# Generated by Django 3.2.9 on 2021-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='delivery_time',
            field=models.IntegerField(default=60),
        ),
    ]
