# Generated by Django 3.2.8 on 2021-11-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(default='https://media.istockphoto.com/photos/food-backgrounds-table-filled-with-large-variety-of-food-picture-id1155240408?k=20&m=1155240408&s=612x612&w=0&h=Zvr3TwVQ-wlfBnvGrgJCtv-_P_LUcIK301rCygnirbk='),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(default='https://restaurantengine.com/wp-content/uploads/2015/05/startup-restaurants-typically-overspend-660x440.jpg'),
        ),
    ]
