# Generated by Django 3.2.8 on 2021-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(default='https://images.everydayhealth.com/images/diet-nutrition/34da4c4e-82c3-47d7-953d-121945eada1e00-giveitup-unhealthyfood.jpg?w=1110', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(default='https://d4t7t8y8xqo0t.cloudfront.net/resized/750X436/eazytrendz%2F1950%2Ftrend20180709030615.jpg', max_length=500),
        ),
    ]
