# Generated by Django 3.2.8 on 2021-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20211112_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
    ]
