# Generated by Django 3.2.8 on 2021-11-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_dish_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stripe_product_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
