# Generated by Django 3.2.9 on 2021-11-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0005_auto_20211127_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.dish'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'dish')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'dish')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='order',
        ),
    ]
