# Generated by Django 3.2.9 on 2021-11-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_customer_address_type'),
        ('seller', '0006_auto_20211127_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'order')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='dish',
        ),
    ]
