# Generated by Django 3.2.8 on 2021-11-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_dish_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
