# Generated by Django 3.2.9 on 2021-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Dish_time',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=FileNotFoundError, max_length=15, null=True),
        ),
    ]
