# Generated by Django 3.2.9 on 2021-11-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20211110_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
