# Generated by Django 3.2.9 on 2021-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20211127_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
