# Generated by Django 3.2.9 on 2021-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_dish_cart'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='dish',
            field=models.ManyToManyField(to='seller.Dish'),
        ),
    ]
