# Generated by Django 3.2.9 on 2021-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartmodel_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='dish',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='order_details',
            field=models.ManyToManyField(to='order.OrderDetails'),
        ),
    ]
