# Generated by Django 3.2.9 on 2021-11-19 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.restaurant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
