# Generated by Django 3.2.8 on 2021-11-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211115_2151'),
        ('order', '0003_auto_20211116_1721'),
    ]

    operations = [
    ]
