# Generated by Django 3.2.9 on 2021-11-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('order', '0004_auto_20211120_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dish',
        ),
        migrations.AddField(
            model_name='cart',
            name='dish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.order'),
        ),
    ]
