# Generated by Django 3.2.9 on 2021-11-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home', max_length=4),
        ),
    ]
